name: Sync Sqlite Database
on: 
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get latest successful run ID
        id: get_run_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_ID="169687509"
          RUN_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=success" \
            | jq '.workflow_runs[0].id')
          echo $RUN_ID
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: database
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: Install dependencies
        run: go mod download
      - name: Run program
        run: go run main.go
        working-directory: cmd/get_pro_leagues
        env:
          STRATZ_API_KEY: ${{ secrets.STRATZ_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: database
          path:  ${{ github.workspace }}/dota-pro-games.db
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create Release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Database"
          files: ./dota-pro-games.db
          prerelease: false
