name: Sync Database
on: [push,workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest successful run ID
        id: get_run_id
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          WORKFLOW_ID="169687509"
          RUN_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=success&branch=main&per_page=1" \
            | jq '.workflow_runs[0].id')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          name: database
          github-token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}
      - name: List files (for debug)
        run: ls -l
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: Install dependencies
        run: go mod download
      - name: Run program
        run: go run main.go
        working-directory: cmd/get_pro_leagues
        env:
          STRATZ_API_KEY: ${{ secrets.STRATZ_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: database
          path:  ${{ github.workspace }}/dota-pro-games.db


